.PHONY: clean All

All:
	@echo "----------Building project:[ simpletron - Debug ]----------"
	@cd "simpletron" && "$(MAKE)" -f  "simpletron.mk"
clean:
	@echo "----------Cleaning project:[ simpletron - Debug ]----------"
	@cd "simpletron" && "$(MAKE)" -f  "simpletron.mk" clean
